---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{PVC_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: kdev
    kdev/name: {{NAME}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{STORAGE_SIZE}}
  storageClassName: {{STORAGE_CLASS}}
  volumeMode: Filesystem
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{SERVICE_ACCOUNT}}
  namespace: {{NAMESPACE}}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: kdev
    kdev/name: {{NAME}}
{{LABELS_EXTRA}}
spec:
  serviceAccountName: {{SERVICE_ACCOUNT}}
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  nodeSelector:
{{NODE_SELECTOR}}
  containers:
    - name: dev
      image: {{IMAGE}}
      workingDir: {{WORKDIR}}
      command: [ "{{SHELL}}", "-lc", "while true; do sleep 3600; done" ]
      env:
{{ENVS}}
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: false
      resources:
        requests:
          cpu: {{CPU}}
          memory: {{MEMORY}}
        limits:
          cpu: {{CPU}}
          memory: {{MEMORY}}
      volumeMounts:
        - name: work
          mountPath: {{WORKDIR}}
  volumes:
    - name: work
      persistentVolumeClaim:
        claimName: {{PVC_NAME}}

